### ISSUE TITLE
own data

### ISSUE THREAD

**Issue by rock19970106** [acfr/cam_lidar_calibration#11]
Hi, if the chessboard is rigid enough, can we calibrate the lidar and camera without a board? Thus , we can set the offset as 0 mm  and  0 mm.

**Comment by darrenjkt** [comment]
I'm not sure what you mean by "if the chessboard is rigid you can calibrate without a board"? If you are referring to the backing board that the chessboard is placed on, then yes you wouldn't need it if your chessboard is very rigid. The main idea is to have a completely flat chessboard surface; how you achieve that is up to you. The offset of the lidar is specific to the internal lidar calibration and not related to the rigidity of the chessboard.
