### ISSUE TITLE
calibration of lidar  which has no 'Ring' value

### ISSUE THREAD

**Issue by blueskych** [acfr/cam_lidar_calibration#12]
Hi,
I am using the lidar which has no value of 'ring',and the scan pattern is different from velydone.  
I saw your source code that it used the 'ring' to get the top left/right and bottom left/right
of the board. So I  want to ask if  there's no "ring" value in my point cloud data, can I use the tool to do calibration?How to do it? 
Thanks.

**Comment by darrenjkt** [comment]
Yes this tool requires the ring value. Scan pattern does not have to be similar to the velodyne. For one of the lidars we had, it had a non-ring like pattern and no ring number provided by the manufacturer. 

To get it to work with this tool, we modified the lidar driver to manually assign ring numbers for each point. For most lidars you should be able to count the number of horizontal lines (i.e. rings) of the lidar FOV.
