### ISSUE TITLE
the question of the chessboard size???

### ISSUE THREAD

**Issue by zuowei1998** [acfr/cam_lidar_calibration#13]
Is the size of the calibration board that can be used just the length and width of the chessboard, and there is no blank edge
57cm*76cm for example
thanks!

**Comment by darrenjkt** [comment]
I'm not sure what you mean by "no blank edge", but regarding the size of the chessboard for calibration, most sizes should work fine. The only issue is that if your chessboard is too small, then you'll have to bring the chessboard closer for the camera to perceive it; this will restrict the calibration range. So ideally, you'd want a chessboard that is big enough but not impractically big.
