### ISSUE TITLE
can you give a detailed picture of the calibration board tripod

### ISSUE THREAD

**Issue by jinjinhong** [acfr/cam_lidar_calibration#14]
hi,Is there a detailed picture of the calibration board tripod? We also want to do a similar。 thank you.

**Comment by darrenjkt** [comment]
Here you go! 

![image](https://user-images.githubusercontent.com/39115809/151286647-ff5f83b2-8b4e-4f67-a3ca-643ed3f131e1.png)

**Comment by jinjinhong** [comment]
thank you
