### ISSUE TITLE
How do you find the intrinsic calibration parameters of the camera?

### ISSUE THREAD

**Issue by arjunskumar** [acfr/cam_lidar_calibration#15]
Can anyone suggest a best tool for mono camera calibration?
I used ros calibration tool but not getting any good results. Is there any best tool available?

**Comment by mendoza-G** [comment]
MATLAB camera calibration APP might help.

**Comment by arjunskumar** [comment]
@mendoza-G Thanks. I was able to get results with ros camera-calibration package
