### ISSUE TITLE
Issue with calibration with my own data

### ISSUE THREAD

**Issue by sou159** [acfr/cam_lidar_calibration#16]
Hi,
I read your paper "Optimising the selection of samples for robust lidar camera calibration" and found it very interesting. I decided to test the available source code. Calibration with your data worked well. However when I tried calibration with my own data using a robosense RS-LiDAR-16 and an ids UI-5280xCP-M mono camera, I faced an issue. In fact, when it comes to feature extraction, The following error appears :
**Connection to node=/feature_extraction failed: param client failed** (Please find below a screen shot of the problem?)

I'm trying to understand the cause of this error, but I don't seem to find it. 
Note1: I can't find "libfeature_extraction.so" in the Lib folder 
Note2: I didn't use a recorded bag file but I used live data instead
Can you please enlighten me on how to solve this problem ?

I would appreciate any help,
Regards,
![Capture d’écran de 2022-03-16 10-38-58](https://user-images.githubusercontent.com/101714926/158629044-022e9dd6-3d64-4ff0-ae6c-a12d443960e5.png)

**Comment by arjunskumar** [comment]
@sou159 are you able to solve?

**Comment by sou159** [comment]
@arjunskumar No, I still have a problem.
I tried data acquisition with the docker environment, but an error appears when it comes to features extraction.
![terminal_msg (1)](https://user-images.githubusercontent.com/101714926/160627197-3d7a7654-6548-4c48-a941-4659a134afbe.png)

**Comment by mendoza-G** [comment]
For note1: I can't find "libfeature_extraction.so" in the Lib folder, it seems the lib is not built successfully, double check the catkin_make log, after deleted build&devel folder. This might be a opencvlib problem.

**Comment by talhasu** [comment]
@sou159 Were you able to solve the issue? I am also having the same problem.

**Comment by duduzai2019** [comment]
> 注意 1：我在 Lib 文件夹中找不到“libfeature_extraction.so”，似乎 lib 没有构建成功，在删除 build&devel 文件夹后仔细检查 catkin_make 日志。这可能是一个 opencvlib 问题。

can it support opencv3?
