### ISSUE TITLE
issue with rosbag play

### ISSUE THREAD

**Issue by talhasu** [acfr/cam_lidar_calibration#18]
Everything works fine until I run rosbag play -l --pause mybag.bag. I am getting the following error. Could you please take a look and reply me back if you know a way around

![issue](https://user-images.githubusercontent.com/62899649/165077802-29e08644-856f-41df-87d0-ca6c38b0a42c.PNG)

**Comment by gara-9527** [comment]
This problem may caused by the `camera_info` topic.
Check if your camera_info topic do exist the intrinsic parameter of your camera.
using `rostopic echo camera_info_topic` to see if this topic contains parameter rather than zero.

**Comment by aristow1** [comment]
@gara-9527 im having the same issue, and i checked rostopic echo camera_info_topic and i get parameters. but i still have the same issue

**Comment by aristow1** [comment]
@talhasu did you get this solved ?

**Comment by gara-9527** [comment]
> @gara-9527 im having the same issue, and i checked rostopic echo camera_info_topic and i get parameters. but i still have the same issue

@aristow1 Can you give me a screenshot of your parameter? Check the parameter and make sure it is correct.For me ,the camera_info_topic's image size doesn't match the real image size cause the issue. 
And this algorithm support online calibration, I personally recommend that you can calibrate online, which can not only save time on recording data, but also facilitate problem solving.

**Comment by aristow1** [comment]
@gara-9527 
![cam_param](https://user-images.githubusercontent.com/84501793/197949694-00d4e43d-2eec-4a57-81a9-49ef795a44f4.pn

the parameters are actually 0 here. should i calibrate the camera myself ? with the ros calibration package ?

**Comment by gara-9527** [comment]
> @gara-9527 ![cam_param](https://user-images.githubusercontent.com/84501793/197950408-2bef854a-9cff-4e75-a7a1-ad1d66a926e8.png)
> 
> the parameters are actually 0 here. should i calibrate the camera myself ? with the ros calibration package ?

Yes,if you don't need high accuracy.I think ros calibration packages is enough.

**Comment by duduzai2019** [comment]
> 一切正常，直到我运行 rosbag play -l --pause mybag.bag。我收到以下错误。如果您知道解决方法，能否请您看一下并回复我
> 
> ![问题](https://user-images.githubusercontent.com/62899649/165077802-29e08644-856f-41df-87d0-ca6c38b0a42c.PNG)

can you slove it ?

**Comment by duduzai2019** [comment]
> 一切正常，直到我运行 rosbag play -l --pause mybag.bag。我收到以下错误。如果您知道解决方法，能否请您看一下并回复我
> 
> ![问题](https://user-images.githubusercontent.com/62899649/165077802-29e08644-856f-41df-87d0-ca6c38b0a42c.PNG)

how can you deal it ? i meet the same problem

**Comment by chinitaberrio** [comment]
Hi @duduzai2019, Did you solve this problem?
