### ISSUE TITLE
Several Approaches and could not get results

### ISSUE THREAD

**Issue by kimjeff-korea** [acfr/cam_lidar_calibration#22]
Thanks for your great result and appreciate for your work again. 

I've tried several approaches, tried in ros Melodic for local environment, also on Docker. Finally I tried to make own environment as this blog says. This blog says that there is something to be modified that I tried the same but I could not get the result.

https://programming.vip/docs/cam-for-joint-calibration-of-lidar-and-camera_-lidar_-calibration.html

But the same result. No data shown on the rviz. (I modified the frame id also.) These are what I have modified and progressed.

I am using Ouster OS-1 32 channel. 

**1. 'Ring Match Problem**
I found out that the ring data is not the same as Velodyne and modified the data type as Ouster.

Modified point.h in ouster_ros official package onto uint16_t

![image](https://user-images.githubusercontent.com/111410819/185037650-73049950-a8f3-4c67-8d5f-70f1d6c2a764.png)

>> Ring not match warning not visible anymore.

**2. Topic Name Configuration**
I've used usb_cam package to publish the camera data on ROS. 
After that I used image_proc as following command.

ROS_NAMESPACE=usb_cam rosrun image_proc image_proc

![image](https://user-images.githubusercontent.com/111410819/185043041-6b7e5dd0-0eb2-42ae-8181-170bbab7f1f4.png)

RQT Graph shows proper data flow for the extraction

**3. Data not shown on rviz**

Two window appears and expected to adjust the thresholds to show only chessboard. But I could not get anymore of progress.

Can anyone give help for the result? Thanks in advance.

**Comment by KyunaCho** [comment]
I'm having the ring match problem. And I'm using os1-64 lidar. Do you know how to remapping the point type?? Please help me.

**Comment by Eeaeau** [comment]
I'm also trying to use an ouster lidar and are also stuck at no data showing in RVIZ. As for the datatype, I think he is believe he is referring to the ouster example [ros driver ](https://github.com/ouster-lidar/ouster_example/blob/3a61f8d9c1a804f8d754c49ead8a4a952b77abdf/ouster_ros/include/ouster_ros/point.h#L25) (I archived similar result by using the ouster point inside this repo instead).

**Comment by jogyul00** [comment]
Finally I can extract the chessboard with 64-ch ouster lidar. In my case, the ROS LiDAR driver's time was different with ROS time. So I just changed the lidar driver code which is ros.cpp in ''ouster_example'' like the screenshot below.
![스크린샷, 2022-11-25 15-36-52](https://user-images.githubusercontent.com/113996397/203917982-3d88c08d-346b-4e2c-b4d9-949a5a9122ce.png)

**Comment by kimjeff-korea** [comment]
In my case, it was something with publishing parameters for camera calibration. When the camera calibration publisher does work well, the codes does a great job. Thanks.
