### ISSUE TITLE
The point cloud is not displayed during the calibration of the ouster radar

### ISSUE THREAD

**Issue by wangdongxu12345** [acfr/cam_lidar_calibration#24]
When I use ouster0-64 lidar for calibration, even if the frame_ The ID and radar topics have been modified, and the data type of ring has been modified to uint16_ t. However, the point cloud cannot be displayed in the calibration interface

**Comment by jclinton830** [comment]
@wangdongxu12345 Can you please state which ROS1 version and Ubuntu version you are using?

PS sorry accidentally closed this issue.

**Comment by jogyul00** [comment]
same issue happens to me.

**Comment by 242726Yuncheng** [comment]
Same issue happens to me. Have you solved this problem?

**Comment by jclinton830** [comment]
> Same issue happens to me. Have you solved this problem?

Can you please state which ROS1 version and Ubuntu version you are using?

**Comment by 242726Yuncheng** [comment]
melodic and Ubuntu 18.04 LTS
