### ISSUE TITLE
error while trying to build the Worspace opencv/cv.hpp

### ISSUE THREAD

**Issue by aristow1** [acfr/cam_lidar_calibration#25]
Hi everyone,
when i try building my workspace i get this error:
fatal error: opencv/cv.hpp: No such file or directory
   10 | #include <opencv/cv.hpp>
      |          ^~~~~~~~~~~~~~~

im using Ubuntu 20.04 and Ros noetic.
any idea on how i can solve this Problem please ?

opencv version is 4.5

**Comment by aristow1** [comment]
appearently the solution is to use Ubuntu 18.04 and ROS melodic. with ROS noetic there are some libraries Issue with the code that are outdated

**Comment by jclinton830** [comment]
> appearently the solution is to use Ubuntu 18.04 and ROS melodic. with ROS noetic there are some libraries Issue with the code that are outdated

@aristow1 Sorry about the delay. Yes, this package currently only works for ROS melodic in ubuntu 18.04. Early next year you can expect it to be released for ROS2.

**Comment by shinianzhihou** [comment]
dear man, is it released for ros2, which is very important for me~
