### ISSUE TITLE
RVIZ shuts down when i capture sample for calibration !

### ISSUE THREAD

**Issue by aristow1** [acfr/cam_lidar_calibration#26]
every time i want to capture the first sample to start the calibration, Rviz shuts down and i have to force quit it. on the terminal the capture seems to be successful and i get this : 
--- Sample 1 ---
Measured board has: dimensions = 610x850 mm; area = 0.51850 m^2
Distance =  1.88 m
Board angles     = 87.15,86.83,87.63,86.36 degrees
Board area       = 0.52148 m^2 (+0.00298 m^2)
Board avg height = 857.69mm (+7.69mm)
Board avg width  = 608.00mm (-2.00mm)
Board dim        = 602.17,855.47,859.90,613.83 mm
Board dim error  =   27.03
 this the error i get when i force quit rviz : 

[rviz-2] process has died [pid 8354, exit code -9, cmd /opt/ros/melodic/lib/rviz/rviz -d /home/****/catkin_ws/src/cam_lidar_calibration/rviz/cam_lidar_calibration.rviz __name:=rviz __log:=/home/****/.ros/log/9cd9ae78-55c8-11ed-880c-d04cc1051f2c/rviz-2.log].
log file: /home/****/.ros/log/9cd9ae78-55c8-11ed-880c-d04cc1051f2c/rviz-2*.log

any help please ?

**Comment by jpk219TW** [comment]
This is a bit of a late reply so I'm not sure if this issue has been solved yet. 
In serviceCB of feature_extractor.cpp, there is a while loop which runs infinitely (not sure what function it serves or why it was included in the first place..). Remove the entire while loop and the package will most likely run fine.

**Comment by aristow1** [comment]
@jpk219TW this solved it thank you.
