### ISSUE TITLE
Error in feature extraction from ouster lidar

### ISSUE THREAD

**Issue by rupikaraj** [acfr/cam_lidar_calibration#32]
I am using this code with a usb cam and ouster os1 lidar on ROS noetic. I used a prerecorded rosbag for the data. 
I have done some changes in the cam_lidar_calibration.rviz. 
` Class: rviz/Image
      Enabled: true
      Image Topic: /cv_camera/image_raw `

and ` Global Options:
    Background Color: 48; 48; 48
    Default Light: true
    Fixed Frame: os_sensor
    Frame Rate: 30 `  so that this code will work for my os1 lidar and camera. While running the launch file for rviz, the image is loading without any issues, but the pointclouds from os_sensor is not loading. Hence the rqt gui is also not working.  I have added the screenshots below. 
![image](https://user-images.githubusercontent.com/105413461/230374939-4d0fc5a9-097d-45c8-afe7-0715202143fd.png)

![image](https://user-images.githubusercontent.com/105413461/230375227-b7b18671-3e2a-46a4-b756-55432a79d227.png)

Can someone please tell me what all changes should i make for my code to work properly? 
Thanks in advance

**Comment by duduzai2019** [comment]
> I am using this code with a usb cam and ouster os1 lidar on ROS noetic. I used a prerecorded rosbag for the data. I have done some changes in the cam_lidar_calibration.rviz. `Class: rviz/Image Enabled: true Image Topic: /cv_camera/image_raw`
> 
> and `Global Options: Background Color: 48; 48; 48 Default Light: true Fixed Frame: os_sensor Frame Rate: 30` so that this code will work for my os1 lidar and camera. While running the launch file for rviz, the image is loading without any issues, but the pointclouds from os_sensor is not loading. Hence the rqt gui is also not working. I have added the screenshots below. ![image](https://user-images.githubusercontent.com/105413461/230374939-4d0fc5a9-097d-45c8-afe7-0715202143fd.png)
> 
> ![image](https://user-images.githubusercontent.com/105413461/230375227-b7b18671-3e2a-46a4-b756-55432a79d227.png)
> 
> Can someone please tell me what all changes should i make for my code to work properly? Thanks in advance
hi, friend, you can change the src/cam_lidar_calibration/cfg/params.yaml    topic ,for example, # camera_topic: "/gmsl/A0/image_color" to lidar_topic: "/rslidar_points"(this is my lidar topic)

**Comment by duduzai2019** [comment]
![image](https://user-images.githubusercontent.com/96464964/232052896-159f0111-8138-4aca-9d40-ec4566e6c721.png)
[feature_extraction-1] process has died [pid 93910, exit code -6, cmd /home/duduzai/SPbot/itsc_calib_ws/devel/lib/cam_lidar_calibration/feature_extraction_node __name:=feature_extraction __log:=/home/duduzai/.ros/log/51abcb48-da75-11ed-8ebb-97b7bce6879a/feature_extraction-1.log].
log file: /home/duduzai/.ros/log/51abcb48-da75-11ed-8ebb-97b7bce6879a/feature_extraction-1*.log

somebody can tell me why? thanks

**Comment by Haishanliu** [comment]
Can someone answer this issue? I still can't find a way to use the ouster data with this pkg. When I try to use the extractor, it doesn't filter the point cloud. 

Thanks in advance.

**Comment by juliangaal** [comment]
It says right there: "width and height of the pattern should have bigger than 2 in function `findChessboardCorners`. Your parameters for the board and/or camera info are wrong.

**Comment by jclinton830** [comment]
@rupikaraj are you collecting data and then playing back along with this tool or are you trying to do the calibration live?

To me it looks like you have not setup the config parameters in the files within the cfg folder properly. If you are still having issues please feel free to reopen this. I am closing it for now.

**Comment by hankge** [comment]
> I am using this code with a usb cam and ouster os1 lidar on ROS noetic. I used a prerecorded rosbag for the data. I have done some changes in the cam_lidar_calibration.rviz. `Class: rviz/Image Enabled: true Image Topic: /cv_camera/image_raw`
> 
> and `Global Options: Background Color: 48; 48; 48 Default Light: true Fixed Frame: os_sensor Frame Rate: 30` so that this code will work for my os1 lidar and camera. While running the launch file for rviz, the image is loading without any issues, but the pointclouds from os_sensor is not loading. Hence the rqt gui is also not working. I have added the screenshots below. ![image](https://user-images.githubusercontent.com/105413461/230374939-4d0fc5a9-097d-45c8-afe7-0715202143fd.png)
> 
> ![image](https://user-images.githubusercontent.com/105413461/230375227-b7b18671-3e2a-46a4-b756-55432a79d227.png)
> 
> Can someone please tell me what all changes should i make for my code to work properly? Thanks in advance

Hi @rupikaraj , I meet the same problem now. Have you find out how to solve this problem?
