### ISSUE TITLE
Help me please.

### ISSUE THREAD

**Issue by SHIN-DONG-UK** [acfr/cam_lidar_calibration#46]
Hello, first of all, thank you for revealing such a useful tool. 
We are using ouster lidar and rgb camera. 
We send image topic using usb_cam (https://github.com/ros-drivers/usb_cam) and pointcloud2 using ouster_lidar(https://github.com/ouster-lidar/ouster-ros). The following problem occurs and I don't know why. Could you please let me know?

![스크린샷, 2023-09-09 19-56-33](https://github.com/acfr/cam_lidar_calibration/assets/140220959/ad59aa95-b2c9-4f85-92a9-0b8f564ac232)
![스크린샷, 2023-09-09 19-56-48](https://github.com/acfr/cam_lidar_calibration/assets/140220959/95684f24-022e-4697-bfd1-531d9e452f70)

**Comment by chinitaberrio** [comment]
Hi @SHIN-DONG-UK , have you changed all the parameters in the config file? that's required for the package to operate properly.
