### ISSUE TITLE
The chessboard has been filtered success. But the RANSAC unsuccessful occurs if i click capture sample

### ISSUE THREAD

**Issue by chenpinganaaa** [acfr/cam_lidar_calibration#49]
When I used the WHEELTEC C16 for radar camera calibration，After the camera publishes the topic successfully, the point cloud filtering process is completed，But RANSAC errors still occur, why? Be akin to Issues#42。
Is WHEELTEC C16 incompatible with this project and needs to be modified？

**Comment by chinitaberrio** [comment]
Hi @chenpinganaaa, we have yet to try the package with the WHEELTEC C16. We could help you if you're able to provide more information about the issue. What rosdriver are you using? Can you show us the filtered point cloud?
