### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [acfr/cam_lidar_calibration#52]
Hi, 

thanks for sharing such wonderful work. I am curious about the improvement of the data selection stage on the baseline algorithm, Besides, I am curious about the comparison on accuracy and performance with the baseline algorithm since I did not see any comparison on your paper.

Thanks

**Comment by jclinton830** [comment]
We are sorry the researcher who wrote this paper has since left our research group. If you have technical issues on how to use the software or want to contribute a PR please open an issue. W are closing this issue for now. Thanks.
