### ISSUE TITLE
Error when running the quickstart using Noetic

### ISSUE THREAD

**Issue by natik-bw** [acfr/cam_lidar_calibration#57]
Interested in reopening issue https://github.com/acfr/cam_lidar_calibration/issues/48#issuecomment-1851148486, as the solution didn't resolve my error.

- I am using ros-noetic, with Opencv-4.5.5 (due to other project dependencies)
- Changing `#include <opencv/cv.hpp>' to '#include <opencv2/opencv.hpp>'
in optimiser.h. It didn't resolve the problem, since it caused the following error when executing `catkin build`:
![image](https://github.com/acfr/cam_lidar_calibration/assets/162879308/ea48da42-aa64-4084-ba09-fe4ff843e249)

I was able to successfully build when I replaced `#include <opencv/cv.hpp>' to:
```
#include <opencv2/core/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/calib3d.hpp>
```

But then, I still got a runtime error when executing the quick start
```roslaunch cam_lidar_calibration run_optimiser.launch import_samples:=true```

![image](https://github.com/acfr/cam_lidar_calibration/assets/162879308/dc9d2287-350c-4cdd-983e-d385729b0e2b)

*** logs ***
[rosout-1-stdout.log](https://github.com/acfr/cam_lidar_calibration/files/15047083/rosout-1-stdout.log)
[rosout.log](https://github.com/acfr/cam_lidar_calibration/files/15047084/rosout.log)
[roslaunch-netanel-Precision-5560-26735.log](https://github.com/acfr/cam_lidar_calibration/files/15047085/roslaunch-netanel-Precision-5560-26735.log)
[master.log](https://github.com/acfr/cam_lidar_calibration/files/15047086/master.log)

***NOTE*** 
I don't know if this is correct, but I used the `calib_v2` branch, and there 
cv::reduce(...) under optimiser.cpp [here](https://github.com/acfr/cam_lidar_calibration/blob/calib-v2/src/optimiser.cpp#L456)
was not commented out (all I had to do was replace CV_REDUCE_SUM by cv::REDUCE_SUM for proper compatibility), so I wasn't sure whether I missed an additional change I had to do.
It wasn't clear to me from @YHuniv 's instructions.

_Originally posted by @natik-bw in https://github.com/acfr/cam_lidar_calibration/issues/48#issuecomment-2067573817_

**Comment by jclinton830** [comment]
Please update your local copy of the repo by checking out noetic_v2 and then doing a git pull. This was fixed recently.
