### ISSUE TITLE
checkerboard is not found

### ISSUE THREAD

**Issue by RBinnenmars** [acfr/cam_lidar_calibration#61]
I am currently wanting to calibrate a camera (Realsense) lidar(Hesai Pandar) combindation, with a checkerboard on a computer monitor([Eizo EV2760-BK Zwart](https://tweakers.net/pricewatch/1530176/eizo-ev2760-bk-zwart.html)), but the screen is not found in the pointcloud. Below is a screenshot where I added the output of the lidar, I needed to change the fixed frame parameter for it to show.

Does anyone know where the error may be? 

![WithPointCloud](https://github.com/acfr/cam_lidar_calibration/assets/45977996/7c680d13-1084-4bb6-8074-5c34febe4543)

**Comment by jclinton830** [comment]
We recommend using a physical checker board for this calibration task. Also, have you calibrated your camera first?
