### ISSUE TITLE
Camera normal in z direction

### ISSUE THREAD

**Issue by dwt189** [acfr/cam_lidar_calibration#8]
As commented in [this line](https://github.com/acfr/cam_lidar_calibration/blob/master/src/feature_extractor.cpp#L665), why is the normal -1 instead of 1 in z?

In my case, using 1 gives the correct results. And thanks for your user-friendly work!

**Comment by darrenjkt** [comment]
It wasn't my choice to change it to -1. We had someone previously refactor the code and this was one of the changes made. My guess is that it might be a specific configuration to cater for how certain cameras/lidars pick up the chessboard (maybe the rotation convention/ left-hand coordinate system or something). Though I apologize I don't have more time to look into this. 

For others who are facing similar issues, it's good that this may be a potential fix.
